version: "3.3"

services:
  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=lireddit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres